# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTopMenu():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_topMenu(self):
    self.driver.get("https://www.spotify.com/kr-ko/")
    self.driver.set_window_size(1288, 1493)
    assert self.driver.find_element(By.XPATH, "//*[@id=\"__next\"]/div[1]/header/div/div[1]/a/span").text == "Spotify"
    assert self.driver.find_element(By.LINK_TEXT, "프리미엄").text == "프리미엄"
    assert self.driver.find_element(By.LINK_TEXT, "지원").text == "지원"
    assert self.driver.find_element(By.LINK_TEXT, "다운로드하기").text == "다운로드하기"
    assert self.driver.find_element(By.LINK_TEXT, "가입하기").text == "가입하기"
    assert self.driver.find_element(By.LINK_TEXT, "로그인하기").text == "로그인하기"
    self.driver.find_element(By.CSS_SELECTOR, ".mh-header-primary > svg").click()
    self.driver.find_element(By.LINK_TEXT, "프리미엄").click()
    assert self.driver.find_element(By.LINK_TEXT, "프리미엄").text == "프리미엄"
    assert self.driver.find_element(By.CSS_SELECTOR, ".bqBVtW .sc-gSYDnn").text == "베이직 요금제에 가입해 Spotify Premium 멤버가 되어보세요. 3개월간 무료로 이용해보세요."
    self.driver.find_element(By.CSS_SELECTOR, ".mh-header-primary > svg").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".sc-gTgzIj").text == "다⁠양⁠한 해⁠외 히⁠트⁠곡⁠과 국⁠내 인⁠기 음⁠악⁠을 들⁠어⁠보⁠세⁠요"
    self.driver.find_element(By.LINK_TEXT, "지원").click()
    assert self.driver.find_element(By.LINK_TEXT, "지원").text == "지원"
    assert self.driver.find_element(By.CSS_SELECTOR, ".itZsWZ").text == "무엇을 도와 드릴까요?"
    self.driver.find_element(By.CSS_SELECTOR, ".mh-header-primary > svg").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".sc-gTgzIj").text == "다⁠양⁠한 해⁠외 히⁠트⁠곡⁠과 국⁠내 인⁠기 음⁠악⁠을 들⁠어⁠보⁠세⁠요"
    self.driver.find_element(By.LINK_TEXT, "다운로드하기").click()
    assert self.driver.find_element(By.LINK_TEXT, "다운로드하기").text == "다운로드하기"
    assert self.driver.find_element(By.CSS_SELECTOR, ".jmMyZK").text == "Spotify 다운로드하기"
    self.driver.find_element(By.CSS_SELECTOR, ".mh-header-primary > svg").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".sc-gTgzIj").text == "다⁠양⁠한 해⁠외 히⁠트⁠곡⁠과 국⁠내 인⁠기 음⁠악⁠을 들⁠어⁠보⁠세⁠요"
    self.driver.find_element(By.LINK_TEXT, "가입하기").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".kpDTub").text == "무료로 가입하고 들어보세요."
    self.driver.get("https://www.spotify.com/kr-ko/")
    assert self.driver.find_element(By.CSS_SELECTOR, ".sc-gTgzIj").text == "다⁠양⁠한 해⁠외 히⁠트⁠곡⁠과 국⁠내 인⁠기 음⁠악⁠을 들⁠어⁠보⁠세⁠요"
    self.driver.find_element(By.LINK_TEXT, "로그인하기").click()
    assert self.driver.find_element(By.ID, "login-to-continue").text == "계속하려면 Spotify에 로그인하세요."
    self.driver.get("https://www.spotify.com/kr-ko/")
    assert self.driver.find_element(By.CSS_SELECTOR, ".sc-gTgzIj").text == "다⁠양⁠한 해⁠외 히⁠트⁠곡⁠과 국⁠내 인⁠기 음⁠악⁠을 들⁠어⁠보⁠세⁠요"
  
