# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBottomarea():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_bottomarea(self):
    self.driver.get("https://www.spotify.com/kr-ko/")
    assert self.driver.find_element(By.LINK_TEXT, "법률 정보").text == "법률 정보"
    assert self.driver.find_element(By.LINK_TEXT, "개인정보 보호 센터").text == "개인정보 보호 센터"
    assert self.driver.find_element(By.LINK_TEXT, "개인정보 처리방침").text == "개인정보 처리방침"
    assert self.driver.find_element(By.LINK_TEXT, "대한민국 (한국어)").text == "대한민국 (한국어)"
    assert self.driver.find_element(By.CSS_SELECTOR, ".svelte-1so9ic8").text == "© 2023 Spotify AB"
    self.driver.find_element(By.LINK_TEXT, "법률 정보").click()
    assert self.driver.find_element(By.XPATH, "//*[@id=\"__next\"]/main/div[2]/p[27]").text == "안녕하십니까. Spotify 이용 약관(\\\"약관\\\")에 오신 것을 환영합니다. 아래 약관은 다음과 같은 이유로 중요합니다."
    self.driver.find_element(By.CSS_SELECTOR, ".mh-header-primary path").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".sc-gTgzIj").text == "다⁠양⁠한 해⁠외 히⁠트⁠곡⁠과 국⁠내 인⁠기 음⁠악⁠을 들⁠어⁠보⁠세⁠요"
    self.driver.find_element(By.LINK_TEXT, "개인정보 보호 센터").click()
    assert self.driver.find_element(By.XPATH, "//*[@id=\"__next\"]/div/div[2]/h1/span").text == "개인정보 보호 센터"
    self.driver.find_element(By.CSS_SELECTOR, ".mh-header-primary path").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".sc-gTgzIj").text == "다⁠양⁠한 해⁠외 히⁠트⁠곡⁠과 국⁠내 인⁠기 음⁠악⁠을 들⁠어⁠보⁠세⁠요"
    self.driver.find_element(By.LINK_TEXT, "개인정보 처리방침").click()
    assert self.driver.find_element(By.XPATH, "//*[@id=\"spotify-개인정보처리방침\"]").text == "Spotify 개인정보처리방침"
    self.driver.find_element(By.CSS_SELECTOR, ".mh-header-primary path").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".sc-gTgzIj").text == "다⁠양⁠한 해⁠외 히⁠트⁠곡⁠과 국⁠내 인⁠기 음⁠악⁠을 들⁠어⁠보⁠세⁠요"
    self.driver.find_element(By.LINK_TEXT, "대한민국 (한국어)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".eOKwwY").text == "국가 또는 지역 선택하기:"
    self.driver.find_element(By.CSS_SELECTOR, ".mh-header-primary path").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".sc-gTgzIj").text == "다⁠양⁠한 해⁠외 히⁠트⁠곡⁠과 국⁠내 인⁠기 음⁠악⁠을 들⁠어⁠보⁠세⁠요"
  
