# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestIntermediatearea():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_intermediatearea(self):
    self.driver.get("https://www.spotify.com/kr-ko/")
    assert self.driver.find_element(By.CSS_SELECTOR, ".sc-gTgzIj").text == "다⁠양⁠한 해⁠외 히⁠트⁠곡⁠과 국⁠내 인⁠기 음⁠악⁠을 들⁠어⁠보⁠세⁠요"
    assert self.driver.find_element(By.CSS_SELECTOR, ".sc-laRPJI").text == "1개의 모바일 기기에서 7일 동안 무료로 Spotify Premium 멤버십을 이용해보세요. 결제 세부 정보는 필요하지 않습니다."
    self.driver.find_element(By.CSS_SELECTOR, ".gjIPUN > img").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".Fd93Bb > span").text == "Spotify (스포티파이) : 음악부터 팟캐스트까지"
    self.driver.get("https://www.spotify.com/kr-ko/")
    self.driver.find_element(By.CSS_SELECTOR, ".bEPcHc > img").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".product-header__subtitle").text == "내 취향에 꼭 맞는 뮤직, 스트리밍부터 다운로드까지"
    self.driver.get("https://www.spotify.com/kr-ko/")
    assert self.driver.find_element(By.CSS_SELECTOR, ".gdCoUB").text == "약관이 적용됩니다. Premium을 이미 이용해 보셨거나 다른 기기로 이용하시려는 경우 이 프로모션을 이용할 수 없습니다. 7일 후에도 계속 Spotify 서비스를 이용하려면 Premium을 구독해야 합니다."
    self.driver.find_element(By.LINK_TEXT, "약관").click()
    assert self.driver.find_element(By.ID, "spotify-이용-약관").text == "Spotify 이용 약관"
    self.driver.get("https://www.spotify.com/kr-ko/")
  
